import { FormEvent, useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, CheckCircle2, Clock3, Database, Mail, Plus, RefreshCw, Save, Server, Settings, ShieldCheck, Users, Wrench } from 'lucide-react'
import { api, formatDate, json } from '../api'
import type { AuditLog, ListResponse, SystemSettings, SystemStatus, User } from '../types'
import { EmptyState, ErrorNotice, Modal, Page, PageHeader, Pager, ReauthFields, Spinner, StatusBadge, SuccessNotice, formatUptime, reauthenticate } from '../components/UI'

export function AdminUsersPage(){
  const queryClient=useQueryClient();const [page,setPage]=useState(1);const [createOpen,setCreateOpen]=useState(false);const [editing,setEditing]=useState<User|null>(null);const [createForm,setCreateForm]=useState({email:'',password:'',role:'user'});const [editForm,setEditForm]=useState({role:'user',status:'active',quota_droplets:'',quota_vcpus:'',quota_memory_mb:''});const [message,setMessage]=useState('');const [createLoginPassword,setCreateLoginPassword]=useState('');const [editLoginPassword,setEditLoginPassword]=useState('')
  const users=useQuery({queryKey:['admin-users',page],queryFn:()=>api<ListResponse<User>>(`/api/v1/admin/users?page=${page}&per_page=20`)})
  const create=useMutation({mutationFn:async()=>{await reauthenticate(createLoginPassword);return api<User>('/api/v1/admin/users',json('POST',createForm))},onSuccess:()=>{queryClient.invalidateQueries({queryKey:['admin-users']});setCreateOpen(false);setCreateForm({email:'',password:'',role:'user'});setCreateLoginPassword('');setMessage('用户已创建')} })
  const update=useMutation({mutationFn:async()=>{await reauthenticate(editLoginPassword);return api<User>(`/api/v1/admin/users/${editing!.id}`,json('PATCH',{role:editForm.role,status:editForm.status,quota_droplets:nullableNumber(editForm.quota_droplets),quota_vcpus:nullableNumber(editForm.quota_vcpus),quota_memory_mb:nullableNumber(editForm.quota_memory_mb)}))},onSuccess:()=>{queryClient.invalidateQueries({queryKey:['admin-users']});setEditing(null);setEditLoginPassword('');setMessage('用户设置已更新')}})
  const openEdit=(user:User)=>{setEditing(user);setEditLoginPassword('');setEditForm({role:user.role,status:user.status,quota_droplets:user.quota_droplets?.toString()||'',quota_vcpus:user.quota_vcpus?.toString()||'',quota_memory_mb:user.quota_memory_mb?.toString()||''})}
  return <Page><PageHeader title="用户管理" subtitle="账号状态、角色与本地资源配额" actions={<button className="button primary" onClick={()=>setCreateOpen(true)}><Plus size={18}/>创建用户</button>}/><SuccessNotice message={message}/><ErrorNotice error={users.error}/>
    {users.isLoading?<Spinner/>:!users.data?.items.length?<EmptyState title="暂无用户"/>:<section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>实例配额</th><th>vCPU 配额</th><th>内存配额</th><th>邮箱验证</th><th>创建时间</th><th/></tr></thead><tbody>{users.data.items.map(user=><tr key={user.id}><td><div className="cell-primary"><span className="avatar">{user.email.slice(0,1).toUpperCase()}</span><span><strong>{user.email}</strong><small className="mono">{user.id.slice(0,8)}</small></span></div></td><td><span className="role-label">{user.role==='admin'?'管理员':'用户'}</span></td><td><StatusBadge value={user.status}/></td><td>{quotaText(user.quota_droplets)}</td><td>{quotaText(user.quota_vcpus)}</td><td>{user.quota_memory_mb===null?'不限':`${user.quota_memory_mb} MB`}</td><td>{user.email_verified_at?formatDate(user.email_verified_at):'未验证'}</td><td>{formatDate(user.created_at)}</td><td><button className="button secondary small" onClick={()=>openEdit(user)}>编辑</button></td></tr>)}</tbody></table></div><Pager page={page} perPage={20} total={users.data.total} onChange={setPage}/></section>}
    {createOpen&&<Modal title="创建用户" onClose={()=>setCreateOpen(false)}><form className="stack-form" onSubmit={e=>{e.preventDefault();create.mutate()}}><label>邮箱<input type="email" required value={createForm.email} onChange={e=>setCreateForm({...createForm,email:e.target.value})}/></label><label>初始密码<input type="password" minLength={12} maxLength={128} required value={createForm.password} onChange={e=>setCreateForm({...createForm,password:e.target.value})}/></label><label>角色<select value={createForm.role} onChange={e=>setCreateForm({...createForm,role:e.target.value})}><option value="user">用户</option><option value="admin">管理员</option></select></label><ReauthFields password={createLoginPassword} onChange={setCreateLoginPassword}/><ErrorNotice error={create.error}/><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setCreateOpen(false)}>取消</button><button className="button primary" disabled={create.isPending}>创建</button></div></form></Modal>}
    {editing&&<Modal title="编辑用户" onClose={()=>setEditing(null)}><form className="stack-form" onSubmit={e=>{e.preventDefault();update.mutate()}}><div className="confirm-summary"><strong>{editing.email}</strong></div><div className="form-grid two"><label>角色<select value={editForm.role} onChange={e=>setEditForm({...editForm,role:e.target.value})}><option value="user">用户</option><option value="admin">管理员</option></select></label><label>状态<select value={editForm.status} onChange={e=>setEditForm({...editForm,status:e.target.value})}><option value="active">正常</option><option value="pending">待验证</option><option value="disabled">停用</option></select></label></div><div className="form-grid three"><label>实例配额<input type="number" min="0" value={editForm.quota_droplets} onChange={e=>setEditForm({...editForm,quota_droplets:e.target.value})} placeholder="不限"/></label><label>vCPU 配额<input type="number" min="0" value={editForm.quota_vcpus} onChange={e=>setEditForm({...editForm,quota_vcpus:e.target.value})} placeholder="不限"/></label><label>内存配额 (MB)<input type="number" min="0" value={editForm.quota_memory_mb} onChange={e=>setEditForm({...editForm,quota_memory_mb:e.target.value})} placeholder="不限"/></label></div><ReauthFields password={editLoginPassword} onChange={setEditLoginPassword}/><ErrorNotice error={update.error}/><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setEditing(null)}>取消</button><button className="button primary" disabled={update.isPending}>保存</button></div></form></Modal>}
  </Page>
}

function nullableNumber(value:string){return value.trim()===''?null:Number(value)}
function quotaText(value:number|null){return value===null?'不限':String(value)}

interface SettingsForm extends SystemSettings { smtp:SystemSettings['smtp']&{password:string;clear_password:boolean} }

export function AdminSettingsPage(){
  const queryClient=useQueryClient();const [form,setForm]=useState<SettingsForm|null>(null);const [message,setMessage]=useState('');const [testOpen,setTestOpen]=useState(false);const [testEmail,setTestEmail]=useState('');const [loginPassword,setLoginPassword]=useState('');const [testError,setTestError]=useState<unknown>(null);const [testing,setTesting]=useState(false);const [saveOpen,setSaveOpen]=useState(false);const [savePassword,setSavePassword]=useState('')
  const settings=useQuery({queryKey:['admin-settings'],queryFn:()=>api<SystemSettings>('/api/v1/admin/settings')})
  useEffect(()=>{if(settings.data)setForm({...settings.data,smtp:{...settings.data.smtp,password:'',clear_password:false}})},[settings.data])
  const save=useMutation({mutationFn:()=>{
    const {password_configured:_,...smtp}=form!.smtp
    return reauthenticate(savePassword).then(()=>api('/api/v1/admin/settings',json('PUT',{...form!,smtp})))
  },onSuccess:()=>{setMessage('系统设置已保存');setSaveOpen(false);setSavePassword('');queryClient.invalidateQueries({queryKey:['admin-settings']});queryClient.invalidateQueries({queryKey:['public-config']})}})
  const testSMTP=async(event:FormEvent)=>{event.preventDefault();setTesting(true);setTestError(null);try{await reauthenticate(loginPassword);await api('/api/v1/admin/settings/smtp/test',json('POST',{to:testEmail}));setTestOpen(false);setMessage('SMTP 测试邮件已发送');setLoginPassword('')}catch(error){setTestError(error)}finally{setTesting(false)}}
  if(settings.isLoading)return <Page><PageHeader title="系统设置"/><Spinner/></Page>
  if(settings.error)return <Page><PageHeader title="系统设置"/><ErrorNotice error={settings.error}/></Page>
  if(!form)return <Page><PageHeader title="系统设置"/><ErrorNotice error={new Error('系统设置响应无效')}/></Page>
  return <Page><PageHeader title="系统设置" subtitle="站点、注册、配额、会话和邮件服务" actions={<button className="button primary" onClick={()=>setSaveOpen(true)} disabled={save.isPending}><Save size={17}/>保存设置</button>}/><SuccessNotice message={message}/><ErrorNotice error={settings.error}/>
    <div className="settings-layout">
      <section className="panel form-section"><div className="section-heading"><div className="heading-icon"><Settings size={19}/></div><div><h2>站点</h2><span>名称和默认时区</span></div></div><div className="form-grid two"><label>站点名称<input maxLength={100} value={form.site.name} onChange={e=>setForm({...form,site:{...form.site,name:e.target.value}})}/></label><label>时区<select value={form.site.timezone} onChange={e=>setForm({...form,site:{...form.site,timezone:e.target.value}})}><option value="Asia/Shanghai">Asia/Shanghai</option><option value="Asia/Hong_Kong">Asia/Hong_Kong</option><option value="Asia/Singapore">Asia/Singapore</option><option value="UTC">UTC</option><option value="America/New_York">America/New_York</option><option value="Europe/London">Europe/London</option></select></label></div></section>
      <section className="panel form-section"><div className="section-heading"><div className="heading-icon"><Users size={19}/></div><div><h2>访问控制</h2><span>公开注册、会话和维护模式</span></div></div><div className="toggle-grid"><label className="switch-row"><span><strong>开放注册</strong><small>允许邮箱自助注册</small></span><input type="checkbox" checked={form.registration.enabled} onChange={e=>setForm({...form,registration:{enabled:e.target.checked}})}/></label><label className="switch-row"><span><strong>维护模式</strong><small>管理员仍可正常访问</small></span><input type="checkbox" checked={form.maintenance.enabled} onChange={e=>setForm({...form,maintenance:{...form.maintenance,enabled:e.target.checked}})}/></label></div><div className="form-grid two"><label>会话有效期（小时）<input type="number" min="1" max={2160} value={form.session.hours} onChange={e=>setForm({...form,session:{hours:Number(e.target.value)}})}/></label><label>维护提示<input value={form.maintenance.message} onChange={e=>setForm({...form,maintenance:{...form.maintenance,message:e.target.value}})}/></label></div></section>
      <section className="panel form-section"><div className="section-heading"><div className="heading-icon"><Server size={19}/></div><div><h2>默认配额</h2><span>新注册用户的本地资源限制</span></div></div><div className="form-grid three"><NullableInput label="实例" value={form.default_quota.droplets} onChange={value=>setForm({...form,default_quota:{...form.default_quota,droplets:value}})}/><NullableInput label="vCPU" value={form.default_quota.vcpus} onChange={value=>setForm({...form,default_quota:{...form.default_quota,vcpus:value}})}/><NullableInput label="内存 (MB)" value={form.default_quota.memory_mb} onChange={value=>setForm({...form,default_quota:{...form.default_quota,memory_mb:value}})}/></div></section>
      <section className="panel form-section"><div className="section-heading"><div className="heading-icon"><Mail size={19}/></div><div><h2>SMTP</h2><span>{form.smtp.password_configured?'密码已配置':'密码未配置'}</span></div><button className="button secondary small" onClick={()=>setTestOpen(true)}><Mail size={16}/>测试已保存配置</button></div><div className="form-grid three"><label>主机<input value={form.smtp.host} onChange={e=>setForm({...form,smtp:{...form.smtp,host:e.target.value}})} placeholder="smtp.example.com"/></label><label>端口<input type="number" min="1" max="65535" value={form.smtp.port} onChange={e=>setForm({...form,smtp:{...form.smtp,port:Number(e.target.value)}})}/></label><label>发件邮箱<input type="email" value={form.smtp.from} onChange={e=>setForm({...form,smtp:{...form.smtp,from:e.target.value}})}/></label><label>用户名<input value={form.smtp.username} onChange={e=>setForm({...form,smtp:{...form.smtp,username:e.target.value}})}/></label><label>新密码<input type="password" value={form.smtp.password} onChange={e=>setForm({...form,smtp:{...form.smtp,password:e.target.value,clear_password:false}})} placeholder={form.smtp.password_configured?'留空保留当前密码':'未设置'}/></label></div><div className="toggle-grid"><label className="switch-row"><span><strong>STARTTLS</strong><small>升级为加密连接</small></span><input type="checkbox" checked={form.smtp.starttls} onChange={e=>setForm({...form,smtp:{...form.smtp,starttls:e.target.checked}})}/></label><label className="switch-row"><span><strong>清除 SMTP 密码</strong><small>保存后删除已托管密码</small></span><input type="checkbox" checked={form.smtp.clear_password} onChange={e=>setForm({...form,smtp:{...form.smtp,clear_password:e.target.checked,password:e.target.checked?'':form.smtp.password}})}/></label></div></section>
    </div>
    {saveOpen&&<Modal title="确认保存系统设置" onClose={()=>setSaveOpen(false)}><form className="stack-form" onSubmit={e=>{e.preventDefault();save.mutate()}}><ReauthFields password={savePassword} onChange={setSavePassword}/><ErrorNotice error={save.error}/><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setSaveOpen(false)}>取消</button><button className="button primary" disabled={save.isPending}><Save size={17}/>确认保存</button></div></form></Modal>}
    {testOpen&&<Modal title="测试已保存的 SMTP 配置" onClose={()=>setTestOpen(false)}><form className="stack-form" onSubmit={testSMTP}><label>收件邮箱<input type="email" required value={testEmail} onChange={e=>setTestEmail(e.target.value)}/></label><ReauthFields password={loginPassword} onChange={setLoginPassword}/><ErrorNotice error={testError}/><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setTestOpen(false)}>取消</button><button className="button primary" disabled={testing}><Mail size={17}/>发送测试</button></div></form></Modal>}
  </Page>
}

function NullableInput({label,value,onChange}:{label:string;value:number|null;onChange:(value:number|null)=>void}){return <label>{label}<input type="number" min="0" value={value??''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))} placeholder="不限"/></label>}

export function AdminStatusPage(){
  const status=useQuery({queryKey:['admin-status'],queryFn:()=>api<SystemStatus>('/api/v1/admin/status'),refetchInterval:15000})
  if(status.isLoading)return <Page><PageHeader title="系统状态"/><Spinner/></Page>
  const data=status.data
  return <Page><PageHeader title="系统状态" subtitle="API、数据库、Worker 和任务队列" actions={<button className="button secondary" onClick={()=>status.refetch()}><RefreshCw className={status.isFetching?'spin':''} size={17}/>刷新</button>}/><ErrorNotice error={status.error}/>{data&&<><section className="metric-grid"><StatusMetric icon={<Activity/>} label="API" value="运行中" ok/><StatusMetric icon={<Database/>} label="PostgreSQL" value={`${data.database.latency_ms} ms`} ok={data.database.ok}/><StatusMetric icon={<Wrench/>} label="Worker" value={data.worker_ok?'在线':'离线'} ok={data.worker_ok}/><StatusMetric icon={<Clock3/>} label="运行时间" value={formatUptime(data.uptime_seconds)} ok/></section><div className="detail-grid"><section className="panel"><div className="section-heading"><h2>运行环境</h2></div><dl className="detail-list"><div><dt>应用版本</dt><dd>{data.version}</dd></div><div><dt>提交</dt><dd className="mono">{data.commit==='unknown'?'--':data.commit.slice(0,12)}</dd></div><div><dt>构建时间</dt><dd>{data.build_time==='unknown'?'--':formatDate(data.build_time)}</dd></div><div><dt>Go</dt><dd>{data.go_version}</dd></div><div><dt>环境</dt><dd>{data.environment}</dd></div><div><dt>迁移版本</dt><dd>{data.database.migration_version}</dd></div></dl></section><section className="panel"><div className="section-heading"><h2>资源计数</h2></div><dl className="detail-list"><div><dt>用户</dt><dd>{data.counts.users||0}</dd></div><div><dt>云账号</dt><dd>{data.counts.accounts||0}</dd></div><div><dt>实例</dt><dd>{data.counts.droplets||0}</dd></div><div><dt>活跃 Worker</dt><dd>{data.counts.active_workers||0}</dd></div></dl></section><section className="panel"><div className="section-heading"><h2>任务队列</h2></div><dl className="detail-list"><div><dt>排队中</dt><dd>{data.counts.queued_jobs||0}</dd></div><div><dt>执行中</dt><dd>{data.counts.running_jobs||0}</dd></div><div><dt>24 小时失败</dt><dd>{data.counts.failed_jobs||0}</dd></div></dl></section></div></>}</Page>
}

function StatusMetric({icon,label,value,ok}:{icon:React.ReactNode;label:string;value:string;ok:boolean}){return <div className="metric"><span className={`metric-icon ${ok?'ok':'bad'}`}>{icon}</span><div><span>{label}</span><strong>{value}</strong><small>{ok?'状态正常':'需要处理'}</small></div></div>}

export function AdminAuditPage(){
  const [page,setPage]=useState(1);const [selected,setSelected]=useState<AuditLog|null>(null);const logs=useQuery({queryKey:['admin-audit',page],queryFn:()=>api<ListResponse<AuditLog>>(`/api/v1/admin/audit-logs?page=${page}&per_page=30`)})
  return <Page><PageHeader title="审计日志" subtitle="登录、账号、实例和管理员操作记录" actions={<button className="button secondary" onClick={()=>logs.refetch()}><RefreshCw className={logs.isFetching?'spin':''} size={17}/>刷新</button>}/><ErrorNotice error={logs.error}/>{logs.isLoading?<Spinner/>:!logs.data?.items.length?<EmptyState title="暂无审计日志"/>:<section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>资源</th><th>目标用户</th><th>IP</th><th/></tr></thead><tbody>{logs.data.items.map(log=><tr key={log.id}><td>{formatDate(log.created_at)}</td><td><strong>{log.actor_email||'系统'}</strong>{log.actor_user_id&&<small className="mono block">{log.actor_user_id.slice(0,8)}</small>}</td><td><span className="audit-action">{log.action}</span></td><td>{log.resource_type}<small className="mono block">{log.resource_id||'--'}</small></td><td className="mono">{log.target_user_id?.slice(0,8)||'--'}</td><td className="mono">{log.ip_address||'--'}</td><td><button className="button secondary small" onClick={()=>setSelected(log)}>详情</button></td></tr>)}</tbody></table></div><Pager page={page} perPage={30} total={logs.data.total} onChange={setPage}/></section>}{selected&&<Modal title={`审计日志 #${selected.id}`} onClose={()=>setSelected(null)}><dl className="detail-list"><div><dt>动作</dt><dd>{selected.action}</dd></div><div><dt>资源</dt><dd>{selected.resource_type} / {selected.resource_id||'--'}</dd></div><div><dt>操作者</dt><dd>{selected.actor_email||'系统'}</dd></div><div><dt>IP</dt><dd>{selected.ip_address||'--'}</dd></div><div><dt>User-Agent</dt><dd className="break-all">{selected.user_agent||'--'}</dd></div></dl><h3>元数据</h3><pre className="json-block">{JSON.stringify(selected.metadata||{},null,2)}</pre></Modal>}</Page>
}
