import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Activity, ArrowLeft, Copy, Cpu, HardDrive, KeyRound, MoreHorizontal, Plus, Power, RefreshCw, Search, Server, ShieldAlert, Trash2, Wifi } from 'lucide-react'
import { api, formatDate, formatMoney, json } from '../api'
import type { CloudAccount, Droplet, Image, ListResponse, Project, Region, SSHKey, Size, VPC } from '../types'
import { EmptyState, ErrorNotice, Modal, Page, PageHeader, ReauthFields, Spinner, StatusBadge, SuccessNotice, formatBytesMB, reauthenticate } from '../components/UI'

const batchActions = [
  ['power_on','开机'],['power_off','强制关机'],['shutdown','正常关机'],['reboot','重启'],['power_cycle','强制重启'],
  ['snapshot','创建快照'],['enable_backups','启用备份'],['disable_backups','停用备份'],['password_reset','重置 root 密码'],
] as const

export default function DropletsPage() {
  const queryClient=useQueryClient(); const navigate=useNavigate()
  const [page,setPage]=useState(1); const [accountFilter,setAccountFilter]=useState(''); const [searchInput,setSearchInput]=useState(''); const [search,setSearch]=useState('')
  const [selected,setSelected]=useState<number[]>([]); const [action,setAction]=useState(''); const [snapshotName,setSnapshotName]=useState(''); const [password,setPassword]=useState(''); const [destroy,setDestroy]=useState(false); const [confirmNames,setConfirmNames]=useState<Record<string,string>>({}); const [operationError,setOperationError]=useState<unknown>(null)
  const accounts=useQuery({queryKey:['accounts'],queryFn:()=>api<ListResponse<CloudAccount>>('/api/v1/cloud-accounts/')})
  const params=new URLSearchParams({page:String(page),per_page:'20'}); if(accountFilter)params.set('account_id',accountFilter);if(search)params.set('search',search)
  const droplets=useQuery({queryKey:['droplets',page,accountFilter,search],queryFn:()=>api<ListResponse<Droplet>>(`/api/v1/droplets/?${params}`)})
  const selectedItems=(droplets.data?.items||[]).filter(item=>selected.includes(item.provider_id)); const selectedAccount=selectedItems[0]?.account_id
  const operation=useMutation({mutationFn:async(input:{kind:'action'|'delete';action?:string})=>{
    if(!selectedAccount)throw new Error('请选择实例')
    if(input.kind==='delete'){
      await reauthenticate(password)
      return api('/api/v1/droplets/delete',json('POST',{account_id:selectedAccount,droplet_ids:selected,confirm_names:confirmNames}))
    }
    if(input.action==='password_reset')await reauthenticate(password)
    const parameters=input.action==='snapshot'&&snapshotName.trim()?{name:snapshotName.trim()}:{ }
    return api('/api/v1/droplets/actions',json('POST',{account_id:selectedAccount,droplet_ids:selected,action:input.action,parameters}))
  },onSuccess:()=>{queryClient.invalidateQueries({queryKey:['jobs']});setAction('');setDestroy(false);setSelected([]);setPassword('');setSnapshotName('');navigate('/jobs')},onError:setOperationError})
  const toggle=(item:Droplet)=>{setOperationError(null);setSelected(current=>{
    if(current.includes(item.provider_id))return current.filter(id=>id!==item.provider_id)
    const first=(droplets.data?.items||[]).find(row=>current.includes(row.provider_id)); if(first&&first.account_id!==item.account_id){setOperationError(new Error('批量操作只能选择同一云账号下的实例'));return current}
    return [...current,item.provider_id]
  })}
  const submitSearch=(event:FormEvent)=>{event.preventDefault();setPage(1);setSearch(searchInput.trim())}
  const openDestroy=()=>{const initial:Record<string,string>={};selectedItems.forEach(item=>initial[String(item.provider_id)]='');setConfirmNames(initial);setPassword('');setOperationError(null);setDestroy(true)}
  const allOnPage=(droplets.data?.items||[]).filter(item=>!selectedAccount||item.account_id===selectedAccount)
  return <Page>
    <PageHeader title="实例" subtitle="DigitalOcean Droplet 生命周期管理" actions={<Link className="button primary" to="/droplets/new"><Plus size={18}/>创建实例</Link>}/>
    <div className="filter-bar"><form className="search-box" onSubmit={submitSearch}><Search size={17}/><input value={searchInput} onChange={e=>setSearchInput(e.target.value)} placeholder="搜索名称或 IPv4"/><button className="button secondary small">搜索</button></form><select value={accountFilter} onChange={e=>{setAccountFilter(e.target.value);setPage(1);setSelected([])}}><option value="">全部云账号</option>{accounts.data?.items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="icon-button bordered" onClick={()=>droplets.refetch()} title="刷新"><RefreshCw className={droplets.isFetching?'spin':''} size={18}/></button></div>
    <ErrorNotice error={droplets.error||accounts.error||operationError}/>
    {selected.length>0&&<div className="selection-toolbar"><span>已选择 <strong>{selected.length}</strong> 台</span><div><select value="" onChange={e=>{setOperationError(null);setPassword('');setAction(e.target.value)}}><option value="">选择批量操作</option>{batchActions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="button danger small" onClick={openDestroy}><Trash2 size={16}/>销毁</button></div></div>}
    {droplets.isLoading?<Spinner/>:!droplets.data?.items.length?<EmptyState title={search||accountFilter?'没有匹配的实例':'尚未同步任何实例'} action={<Link className="button primary" to="/droplets/new"><Plus size={17}/>创建实例</Link>}/>:<section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th className="check-cell"><input type="checkbox" checked={allOnPage.length>0&&allOnPage.every(item=>selected.includes(item.provider_id))} onChange={e=>setSelected(e.target.checked?allOnPage.map(item=>item.provider_id):[])}/></th><th>实例</th><th>状态</th><th>网络</th><th>规格</th><th>区域</th><th>费用</th><th>同步时间</th><th/></tr></thead><tbody>{droplets.data.items.map(item=><tr key={item.id} className={selected.includes(item.provider_id)?'selected-row':''}><td className="check-cell"><input type="checkbox" checked={selected.includes(item.provider_id)} onChange={()=>toggle(item)}/></td><td><div className="cell-primary"><span className="resource-icon"><Server size={17}/></span><span><strong>{item.name}</strong><small>#{item.provider_id}</small></span></div></td><td><StatusBadge value={item.status}/>{item.locked&&<small className="danger-text block">操作锁定</small>}</td><td><strong className="mono">{item.ipv4||'无公网 IPv4'}</strong>{item.ipv6&&<small className="mono block">{item.ipv6}</small>}</td><td><strong>{item.vcpus} vCPU · {formatBytesMB(item.memory_mb)}</strong><small className="block">{item.size_slug} · {item.disk_gb} GB</small></td><td>{item.region_slug||'--'}</td><td>{formatMoney(item.price_monthly)}<small className="block">/ 月</small></td><td>{formatDate(item.synced_at)}</td><td><Link className="icon-button bordered" to={`/droplets/${item.id}`} aria-label="查看实例"><MoreHorizontal size={18}/></Link></td></tr>)}</tbody></table></div><div className="pager"><span>第 {page} 页，共 {droplets.data.total} 台</span><div><button className="button secondary small" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><button className="button secondary small" disabled={page*20>=droplets.data.total} onClick={()=>setPage(page+1)}>下一页</button></div></div></section>}
    {action&&<Modal title={batchActions.find(item=>item[0]===action)?.[1]||'实例操作'} onClose={()=>setAction('')}><form className="stack-form" onSubmit={e=>{e.preventDefault();operation.mutate({kind:'action',action})}}><div className="confirm-summary">将对 <strong>{selected.length}</strong> 台实例执行此操作</div>{action==='snapshot'&&<label>快照名称<input value={snapshotName} onChange={e=>setSnapshotName(e.target.value)} placeholder="留空则自动生成"/></label>}{action==='password_reset'&&<><div className="notice warning compact"><ShieldAlert size={17}/><span>DigitalOcean 会将新密码发送至账号邮箱，系统内原有托管密码将标记为需更新。</span></div><ReauthFields password={password} onChange={setPassword}/></>}<ErrorNotice error={operationError}/><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setAction('')}>取消</button><button className="button primary" disabled={operation.isPending}>确认执行</button></div></form></Modal>}
    {destroy&&<Modal title="销毁实例" onClose={()=>setDestroy(false)}><form className="stack-form" onSubmit={e=>{e.preventDefault();operation.mutate({kind:'delete'})}}><div className="notice error compact"><Trash2 size={17}/><span>实例及其本地托管密码将永久删除。</span></div>{selectedItems.map(item=><label key={item.id}>输入实例名称 <strong>{item.name}</strong><input value={confirmNames[String(item.provider_id)]||''} onChange={e=>setConfirmNames({...confirmNames,[String(item.provider_id)]:e.target.value})} required/></label>)}<ReauthFields password={password} onChange={setPassword}/><ErrorNotice error={operationError}/><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setDestroy(false)}>取消</button><button className="button danger" disabled={operation.isPending||selectedItems.some(item=>confirmNames[String(item.provider_id)]!==item.name)}>永久销毁</button></div></form></Modal>}
  </Page>
}

interface CatalogBundle { regions:Region[];sizes:Size[];images:Image[];projects:Project[];vpcs:VPC[];sshKeys:SSHKey[] }

async function loadCatalog(accountId:string):Promise<CatalogBundle>{
  const [regions,sizes,images,projects,vpcs,keys]=await Promise.all([
    api<{regions:Region[]}>(`/api/v1/cloud-accounts/${accountId}/catalog/regions?per_page=200`),api<{sizes:Size[]}>(`/api/v1/cloud-accounts/${accountId}/catalog/sizes?per_page=200`),api<{images:Image[]}>(`/api/v1/cloud-accounts/${accountId}/catalog/images?per_page=200`),api<{projects:Project[]}>(`/api/v1/cloud-accounts/${accountId}/catalog/projects?per_page=200`),api<{vpcs:VPC[]}>(`/api/v1/cloud-accounts/${accountId}/catalog/vpcs?per_page=200`),api<{ssh_keys:SSHKey[]}>(`/api/v1/cloud-accounts/${accountId}/catalog/ssh-keys?per_page=200`),
  ]);return{regions:regions.regions||[],sizes:sizes.sizes||[],images:images.images||[],projects:projects.projects||[],vpcs:vpcs.vpcs||[],sshKeys:keys.ssh_keys||[]}
}

export function CreateDropletPage(){
  const navigate=useNavigate();const queryClient=useQueryClient();const [form,setForm]=useState({account_id:'',names:'',region:'',size:'',image:'',auth_mode:'ssh_keys',ssh_keys:[] as number[],project_id:'',vpc_uuid:'',tags:'',backups:false,ipv6:true,monitoring:true,public_networking:true});const [error,setError]=useState<unknown>(null);const [submitting,setSubmitting]=useState(false)
  const accounts=useQuery({queryKey:['accounts'],queryFn:()=>api<ListResponse<CloudAccount>>('/api/v1/cloud-accounts/')})
  const catalog=useQuery({queryKey:['create-catalog',form.account_id],queryFn:()=>loadCatalog(form.account_id),enabled:!!form.account_id})
  useEffect(()=>{if(!form.account_id&&accounts.data?.items.length){const preferred=accounts.data.items.find(item=>item.credential_status==='valid');if(preferred)setForm(current=>({...current,account_id:preferred.id}))}},[accounts.data,form.account_id])
  useEffect(()=>{if(!catalog.data)return;setForm(current=>{const region=current.region||catalog.data!.regions.find(item=>item.available)?.slug||'';const sizeValid=catalog.data!.sizes.some(item=>item.slug===current.size&&item.available&&(!region||item.regions.includes(region)));const size=sizeValid?current.size:catalog.data!.sizes.find(item=>item.available&&(!region||item.regions.includes(region)))?.slug||'';const imageValid=catalog.data!.images.some(item=>(item.slug||String(item.id))===current.image&&(!region||item.regions.includes(region)));const image=imageValid?current.image:(catalog.data!.images.find(item=>item.slug&&(!region||item.regions.includes(region)))?.slug||'');return{...current,region,size,image}})},[catalog.data])
  const regions=catalog.data?.regions.filter(item=>item.available)||[];const sizes=catalog.data?.sizes.filter(item=>item.available&&(!form.region||item.regions.includes(form.region)))||[];const images=catalog.data?.images.filter(item=>item.status==='available'&&(!form.region||item.regions.includes(form.region)))||[];const vpcs=catalog.data?.vpcs.filter(item=>!form.region||item.region===form.region)||[]
  const names=useMemo(()=>form.names.split(/[\n,]+/).map(value=>value.trim()).filter(Boolean),[form.names]);const selectedSize=sizes.find(item=>item.slug===form.size)
  const submit=async(event:FormEvent)=>{event.preventDefault();setError(null);if(names.length<1||names.length>10){setError(new Error('请输入 1 到 10 个实例名称'));return}if(form.auth_mode==='ssh_keys'&&!form.ssh_keys.length){setError(new Error('请至少选择一个 SSH 公钥'));return}setSubmitting(true);try{await api('/api/v1/droplets/',json('POST',{account_id:form.account_id,names,region:form.region,size:form.size,image:form.image,ssh_keys:form.auth_mode==='ssh_keys'?form.ssh_keys:[],backups:form.backups,backup_policy:{},ipv6:form.ipv6,monitoring:form.monitoring,tags:form.tags.split(',').map(value=>value.trim()).filter(Boolean),vpc_uuid:form.vpc_uuid,project_id:form.project_id,auth_mode:form.auth_mode,public_networking:form.public_networking}));queryClient.invalidateQueries({queryKey:['jobs']});navigate('/jobs')}catch(err){setError(err)}finally{setSubmitting(false)}}
  return <Page><div className="breadcrumb"><Link to="/droplets"><ArrowLeft size={16}/>实例</Link></div><PageHeader title="创建实例" subtitle="单个 DigitalOcean 账号每次最多创建 10 台"/>
    <form className="create-layout" onSubmit={submit}><div className="form-main">
      <section className="panel form-section"><div className="section-heading"><div><span className="step-number">1</span><h2>账号与名称</h2></div></div><div className="form-grid two"><label>云账号<select value={form.account_id} onChange={e=>setForm({...form,account_id:e.target.value,region:'',size:'',image:'',ssh_keys:[],vpc_uuid:'',project_id:''})} required><option value="">请选择</option>{accounts.data?.items.filter(item=>item.credential_status==='valid').map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>实例数量<input value={names.length?`${names.length} 台`:'0 台'} disabled/></label></div><label>实例名称<textarea rows={5} value={form.names} onChange={e=>setForm({...form,names:e.target.value})} placeholder={'web-01\nweb-02'} required/><small>每行一个名称，只允许字母、数字、点和连字符</small></label></section>
      <section className="panel form-section"><div className="section-heading"><div><span className="step-number">2</span><h2>区域与规格</h2></div></div>{catalog.isLoading?<Spinner label="正在读取 DigitalOcean 资源目录"/>:<ErrorNotice error={catalog.error}/>}<div className="form-grid two"><label>区域<select value={form.region} onChange={e=>setForm({...form,region:e.target.value,size:'',image:'',vpc_uuid:''})} required><option value="">请选择</option>{regions.map(item=><option key={item.slug} value={item.slug}>{item.name} ({item.slug})</option>)}</select></label><label>规格<select value={form.size} onChange={e=>setForm({...form,size:e.target.value})} required><option value="">请选择</option>{sizes.map(item=><option key={item.slug} value={item.slug}>{item.slug} · {item.vcpus} vCPU · {formatBytesMB(item.memory)} · {formatMoney(item.price_monthly)}/月</option>)}</select></label></div>{selectedSize&&<div className="spec-strip"><span><Cpu size={16}/>{selectedSize.vcpus} vCPU</span><span><Activity size={16}/>{formatBytesMB(selectedSize.memory)} 内存</span><span><HardDrive size={16}/>{selectedSize.disk} GB SSD</span><strong>{formatMoney(selectedSize.price_monthly)}/月</strong></div>}</section>
      <section className="panel form-section"><div className="section-heading"><div><span className="step-number">3</span><h2>镜像与登录</h2></div></div><label>系统镜像<select value={form.image} onChange={e=>setForm({...form,image:e.target.value})} required><option value="">请选择</option>{images.map(item=><option key={item.id} value={item.slug||item.id}>{item.distribution} · {item.name}</option>)}</select></label><div className="segmented"><button type="button" className={form.auth_mode==='ssh_keys'?'active':''} onClick={()=>setForm({...form,auth_mode:'ssh_keys'})}><KeyRound size={17}/>SSH 公钥</button><button type="button" className={form.auth_mode==='root_password'?'active':''} onClick={()=>setForm({...form,auth_mode:'root_password'})}><ShieldAlert size={17}/>托管 root 密码</button></div>{form.auth_mode==='ssh_keys'?<div className="option-list">{catalog.data?.sshKeys.length?catalog.data.sshKeys.map(key=><label className="check-row option-row" key={key.id}><input type="checkbox" checked={form.ssh_keys.includes(key.id)} onChange={e=>setForm({...form,ssh_keys:e.target.checked?[...form.ssh_keys,key.id]:form.ssh_keys.filter(id=>id!==key.id)})}/><span><strong>{key.name}</strong><small className="mono">{key.fingerprint}</small></span></label>):<div className="notice warning compact">所选账号没有 SSH 公钥，请先在云账号页面添加。</div>}</div>:<div className="notice warning compact"><ShieldAlert size={17}/><span>系统将生成强密码，通过 cloud-init 写入，并使用主密钥加密保存。</span></div>}</section>
      <section className="panel form-section"><div className="section-heading"><div><span className="step-number">4</span><h2>网络与附加选项</h2></div></div><div className="form-grid two"><label>VPC<select value={form.vpc_uuid} onChange={e=>setForm({...form,vpc_uuid:e.target.value})}><option value="">区域默认 VPC</option>{vpcs.map(item=><option value={item.id} key={item.id}>{item.name} · {item.ip_range}</option>)}</select></label><label>项目<select value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">不指定项目</option>{catalog.data?.projects.map(item=><option value={item.id} key={item.id}>{item.name}{item.is_default?'（默认）':''}</option>)}</select></label><label>标签<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="production, web"/></label></div><div className="toggle-grid"><label className="switch-row"><span><strong>公网网络</strong><small>分配公网地址</small></span><input type="checkbox" checked={form.public_networking} onChange={e=>setForm({...form,public_networking:e.target.checked})}/></label><label className="switch-row"><span><strong>IPv6</strong><small>启用 IPv6 网络</small></span><input type="checkbox" checked={form.ipv6} onChange={e=>setForm({...form,ipv6:e.target.checked})}/></label><label className="switch-row"><span><strong>监控</strong><small>安装 DigitalOcean Agent</small></span><input type="checkbox" checked={form.monitoring} onChange={e=>setForm({...form,monitoring:e.target.checked})}/></label><label className="switch-row"><span><strong>备份</strong><small>启用自动备份</small></span><input type="checkbox" checked={form.backups} onChange={e=>setForm({...form,backups:e.target.checked})}/></label></div></section>
    </div><aside className="create-summary"><div className="panel sticky-panel"><h2>创建摘要</h2><dl className="detail-list"><div><dt>账号</dt><dd>{accounts.data?.items.find(item=>item.id===form.account_id)?.name||'未选择'}</dd></div><div><dt>数量</dt><dd>{names.length} 台</dd></div><div><dt>区域</dt><dd>{form.region||'未选择'}</dd></div><div><dt>规格</dt><dd>{form.size||'未选择'}</dd></div><div><dt>预计月费</dt><dd>{selectedSize?formatMoney(selectedSize.price_monthly*Math.max(1,names.length)):'--'}</dd></div></dl><ErrorNotice error={error}/><button className="button primary full" disabled={submitting||catalog.isLoading||!form.account_id}>{submitting?<RefreshCw className="spin" size={17}/>:<Plus size={17}/>}创建实例</button></div></aside></form>
  </Page>
}

export function DropletDetailPage(){
  const {dropletId=''}=useParams()
  return <Page><div className="breadcrumb"><Link to="/droplets"><ArrowLeft size={16}/>实例</Link></div><PageHeader title="实例详情"/><DropletDetailContent dropletId={dropletId}/></Page>
}

function DropletDetailContent({dropletId}:{dropletId:string}){
  const queryClient=useQueryClient();const navigate=useNavigate()
  const [mode,setMode]=useState<string|null>(null);const [loginPassword,setLoginPassword]=useState('');const [managedPassword,setManagedPassword]=useState('');const [revealed,setRevealed]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState<unknown>(null);const [working,setWorking]=useState(false);const [remoteTab,setRemoteTab]=useState<'actions'|'backups'|'snapshots'|'backup-policy'>('actions')
  const [parameters,setParameters]=useState<Record<string,any>>({})
  const query=useQuery({queryKey:['droplet',dropletId],queryFn:()=>api<{droplet:Droplet;root_credential_status:string}>(`/api/v1/droplets/${dropletId}`),enabled:!!dropletId})
  const item=query.data?.droplet
  const sizes=useQuery({queryKey:['account-catalog',item?.account_id,'sizes'],queryFn:()=>api<{sizes:Size[]}>(`/api/v1/cloud-accounts/${item!.account_id}/catalog/sizes?per_page=200`),enabled:!!item&&mode==='resize'})
  const images=useQuery({queryKey:['account-catalog',item?.account_id,'images'],queryFn:()=>api<{images:Image[]}>(`/api/v1/cloud-accounts/${item!.account_id}/catalog/images?per_page=200`),enabled:!!item&&mode==='rebuild'})
  const remote=useQuery({queryKey:['droplet-remote',dropletId,remoteTab],queryFn:()=>api<Record<string,any>>(`/api/v1/droplets/${dropletId}/remote/${remoteTab}?per_page=50`),enabled:!!item})
  if(query.isLoading)return <Spinner/>
  if(query.error||!query.data||!item)return <ErrorNotice error={query.error||new Error('实例不存在')}/>
  const dangerous=new Set(['password_reset','resize','rebuild','restore'])
  const resetModal=()=>{setMode(null);setLoginPassword('');setManagedPassword('');setRevealed('');setParameters({});setError(null)}
  const openAction=(action:string)=>{setMode(action);setError(null);setLoginPassword('');setParameters(action==='rename'?{name:item.name}:action==='resize'?{size:item.size_slug||'',disk:false}:action==='snapshot'?{name:`${item.name}-${new Date().toISOString().slice(0,10)}`}:{})}
  const run=async(event:FormEvent)=>{event.preventDefault();if(!mode)return;setWorking(true);setError(null);setMessage('');try{
    if(mode==='reveal'){await reauthenticate(loginPassword);const result=await api<{password:string}>(`/api/v1/droplets/${dropletId}/root-credential`);setRevealed(result.password);return}
    if(mode==='update-credential'){await reauthenticate(loginPassword);await api(`/api/v1/droplets/${dropletId}/root-credential`,json('PUT',{password:managedPassword}));setMessage('root 密码托管记录已更新');resetModal();queryClient.invalidateQueries({queryKey:['droplet',dropletId]});return}
    if(mode==='delete'){await reauthenticate(loginPassword);await api('/api/v1/droplets/delete',json('POST',{account_id:item.account_id,droplet_ids:[item.provider_id],confirm_names:{[String(item.provider_id)]:parameters.confirm_name||''}}));queryClient.invalidateQueries({queryKey:['jobs']});navigate('/jobs');return}
    if(dangerous.has(mode))await reauthenticate(loginPassword)
    const cleaned={...parameters};if(mode==='restore')cleaned.image=Number(cleaned.image);if(mode==='rebuild'&&/^\d+$/.test(String(cleaned.image)))cleaned.image=Number(cleaned.image)
    await api('/api/v1/droplets/actions',json('POST',{account_id:item.account_id,droplet_ids:[item.provider_id],action:mode,parameters:cleaned}));queryClient.invalidateQueries({queryKey:['jobs']});navigate('/jobs')
  }catch(err){setError(err)}finally{setWorking(false)}}
  const remoteRecords:Array<Record<string,any>>=remoteTab==='backup-policy'?(remote.data?.policy?[remote.data.policy]:[]):(remote.data?.[remoteTab]||remote.data?.images||[])
  return <>
    <PageHeader title={item.name} subtitle={`DigitalOcean #${item.provider_id}`} actions={<><button className="button secondary" onClick={()=>openAction(item.status==='active'?'shutdown':'power_on')}><Power size={17}/>{item.status==='active'?'关机':'开机'}</button><button className="button secondary" onClick={()=>openAction('reboot')}><RefreshCw size={17}/>重启</button><button className="button danger" onClick={()=>{setParameters({confirm_name:''});setMode('delete')}}><Trash2 size={17}/>销毁</button></>}/>
    <SuccessNotice message={message}/><ErrorNotice error={error}/>
    <section className="panel"><div className="section-heading"><div className="cell-primary"><span className="resource-icon large"><Server size={22}/></span><span><h2>{item.name}</h2><small>同步于 {formatDate(item.synced_at)}</small></span></div><StatusBadge value={item.status}/></div><dl className="detail-list detail-columns"><div><dt>IPv4</dt><dd><button className="copy-value mono" onClick={()=>item.ipv4&&navigator.clipboard.writeText(item.ipv4)}>{item.ipv4||'--'}{item.ipv4&&<Copy size={14}/>}</button></dd></div><div><dt>IPv6</dt><dd className="mono">{item.ipv6||'--'}</dd></div><div><dt>区域</dt><dd>{item.region_slug||'--'}</dd></div><div><dt>规格</dt><dd>{item.size_slug||'--'}</dd></div><div><dt>vCPU</dt><dd>{item.vcpus}</dd></div><div><dt>内存</dt><dd>{formatBytesMB(item.memory_mb)}</dd></div><div><dt>磁盘</dt><dd>{item.disk_gb} GB</dd></div><div><dt>月费</dt><dd>{formatMoney(item.price_monthly)}</dd></div><div><dt>镜像</dt><dd>{item.image?.distribution||item.image?.name||item.image?.slug||'--'}</dd></div><div><dt>VPC</dt><dd className="mono">{item.vpc_uuid||'--'}</dd></div><div><dt>项目</dt><dd className="mono">{item.project_id||'未指定'}</dd></div><div><dt>标签</dt><dd>{item.tags?.join(', ')||'--'}</dd></div></dl></section>

    <div className="detail-grid">
      <section className="panel"><div className="section-heading"><div><h2>生命周期操作</h2><span>操作将进入后台任务队列</span></div></div><div className="action-grid"><button onClick={()=>openAction('power_on')}><Power size={18}/><span>开机</span></button><button onClick={()=>openAction('shutdown')}><Power size={18}/><span>正常关机</span></button><button onClick={()=>openAction('power_off')}><ShieldAlert size={18}/><span>强制关机</span></button><button onClick={()=>openAction('power_cycle')}><RefreshCw size={18}/><span>强制重启</span></button><button onClick={()=>openAction('rename')}><Server size={18}/><span>重命名</span></button><button onClick={()=>openAction('resize')}><Cpu size={18}/><span>调整规格</span></button><button onClick={()=>openAction('snapshot')}><HardDrive size={18}/><span>创建快照</span></button><button onClick={()=>openAction('rebuild')}><RefreshCw size={18}/><span>重建系统</span></button><button onClick={()=>openAction('restore')}><HardDrive size={18}/><span>恢复备份</span></button><button onClick={()=>openAction('password_reset')}><KeyRound size={18}/><span>重置密码</span></button><button onClick={()=>openAction('enable_backups')}><Activity size={18}/><span>启用备份</span></button><button onClick={()=>openAction('disable_backups')}><Activity size={18}/><span>停用备份</span></button></div></section>
      <section className="panel"><div className="section-heading"><div><h2>root 凭据保险库</h2><span>AES-256-GCM 加密存储</span></div><StatusBadge value={query.data.root_credential_status}/></div><div className="credential-box"><KeyRound size={26}/><div><strong>{query.data.root_credential_status==='none'?'未托管 root 密码':'root 密码已托管'}</strong><small>{query.data.root_credential_status==='stale'?'远程密码已变化，请更新托管记录':'查看和更新均需重新验证'}</small></div></div><div className="button-row"><button className="button secondary" disabled={query.data.root_credential_status==='none'} onClick={()=>setMode('reveal')}><KeyRound size={17}/>查看密码</button><button className="button secondary" onClick={()=>setMode('update-credential')}><RefreshCw size={17}/>更新记录</button></div></section>
    </div>

    <section className="panel"><div className="section-heading"><div><h2>远程资源</h2><span>直接读取 DigitalOcean API</span></div></div><div className="tabs">{([['actions','操作记录'],['backups','备份'],['snapshots','快照'],['backup-policy','备份策略']] as const).map(([value,label])=><button className={remoteTab===value?'active':''} key={value} onClick={()=>setRemoteTab(value)}>{label}</button>)}</div>{remote.isLoading?<Spinner/>:<ErrorNotice error={remote.error}/>} {remote.data&&(!remoteRecords.length?<EmptyState title="暂无记录"/>:<div className="table-wrap"><table><thead><tr><th>ID</th><th>名称 / 类型</th><th>状态</th><th>创建时间</th></tr></thead><tbody>{remoteRecords.map((record,index)=><tr key={String(record.id||index)}><td className="mono">{String(record.id||'--')}</td><td><strong>{String(record.name||record.type||record.weekday||'--')}</strong></td><td><StatusBadge value={String(record.status||'active')}/></td><td>{record.created_at?formatDate(String(record.created_at)):'--'}</td></tr>)}</tbody></table></div>)}</section>

    {mode&&<Modal title={detailActionTitle(mode)} onClose={resetModal}><form className="stack-form" onSubmit={run}>
      {mode==='rename'&&<label>新名称<input value={parameters.name||''} onChange={e=>setParameters({...parameters,name:e.target.value})} required/></label>}
      {mode==='resize'&&<><label>新规格<select value={parameters.size||''} onChange={e=>setParameters({...parameters,size:e.target.value})} required><option value="">请选择</option>{sizes.data?.sizes.filter(size=>size.available&&(!item.region_slug||size.regions.includes(item.region_slug))).map(size=><option key={size.slug} value={size.slug}>{size.slug} · {size.vcpus} vCPU · {formatBytesMB(size.memory)} · {formatMoney(size.price_monthly)}/月</option>)}</select></label><label className="check-row"><input type="checkbox" checked={!!parameters.disk} onChange={e=>setParameters({...parameters,disk:e.target.checked})}/><span>永久扩容磁盘</span></label></>}
      {mode==='rebuild'&&<label>系统镜像<select value={parameters.image||''} onChange={e=>setParameters({...parameters,image:e.target.value})} required><option value="">请选择</option>{images.data?.images.filter(image=>image.status==='available'&&(!item.region_slug||image.regions.includes(item.region_slug))).map(image=><option key={image.id} value={image.slug||image.id}>{image.distribution} · {image.name}</option>)}</select></label>}
      {mode==='snapshot'&&<label>快照名称<input value={parameters.name||''} onChange={e=>setParameters({...parameters,name:e.target.value})} required/></label>}
      {mode==='restore'&&<label>备份镜像 ID<input type="number" min="1" value={parameters.image||''} onChange={e=>setParameters({...parameters,image:e.target.value})} required/></label>}
      {mode==='delete'&&<><div className="notice error compact"><Trash2 size={17}/><span>实例将被永久销毁，此操作不可撤销。</span></div><label>输入实例名称 <strong>{item.name}</strong><input value={parameters.confirm_name||''} onChange={e=>setParameters({...parameters,confirm_name:e.target.value})} required/></label></>}
      {mode==='password_reset'&&<div className="notice warning compact"><ShieldAlert size={17}/><span>新密码将由 DigitalOcean 发送至账号邮箱，当前托管记录会标记为需更新。</span></div>}
      {mode==='update-credential'&&<label>新的 root 密码<input type="password" minLength={12} maxLength={128} value={managedPassword} onChange={e=>setManagedPassword(e.target.value)} required autoComplete="new-password"/></label>}
      {mode==='reveal'&&revealed?<div className="revealed-secret"><span>root 密码</span><div><code>{revealed}</code><button type="button" className="icon-button" onClick={()=>navigator.clipboard.writeText(revealed)} title="复制"><Copy size={17}/></button></div></div>:<>{(dangerous.has(mode)||mode==='delete'||mode==='reveal'||mode==='update-credential')&&<ReauthFields password={loginPassword} onChange={setLoginPassword}/>}</>}
      <ErrorNotice error={error}/><div className="modal-actions"><button type="button" className="button secondary" onClick={resetModal}>关闭</button>{!(mode==='reveal'&&revealed)&&<button className={`button ${mode==='delete'?'danger':'primary'}`} disabled={working||(mode==='delete'&&parameters.confirm_name!==item.name)}>{working?<RefreshCw className="spin" size={17}/>:null}确认执行</button>}</div>
    </form></Modal>}
  </>
}

function detailActionTitle(action:string){const labels:Record<string,string>={power_on:'开机',power_off:'强制关机',shutdown:'正常关机',reboot:'重启',power_cycle:'强制重启',rename:'重命名实例',resize:'调整实例规格',snapshot:'创建快照',rebuild:'重建系统',restore:'恢复备份',password_reset:'重置 root 密码',enable_backups:'启用备份',disable_backups:'停用备份',delete:'永久销毁实例',reveal:'查看 root 密码','update-credential':'更新 root 密码记录'};return labels[action]||'实例操作'}
